train_config:
  labels: data/processed/small_set_labels.csv
  model_name: time_distributed
  auto_lr_find: True
  backbone_finetune_config:
    backbone_initial_ratio_lr: 0.01
    multiplier: 1
    pre_train_bn: True
    train_bn: False
    unfreeze_backbone_at_epoch: 3
    verbose: True
  batch_size: 1
  from_scratch: True
  save_directory: experiments/td_small_set_full_size_mdlite/results
  skip_load_validation: True
  split_proportions:
  num_workers: 5
  gpus: 1
  early_stopping_config:
    patience: 5
  scheduler_config:
    scheduler: MultiStepLR
    scheduler_params:
      gamma: 0.5
      milestones:
      - 3
      verbose: true

video_loader_config:
  model_input_height: 240
  model_input_width: 426
  crop_bottom_pixels: 50
  fps: 4
  total_frames: 16
  ensure_total_frames: True
  megadetector_lite_config:
    confidence: 0.25
    fill_mode: score_sorted
    n_frames: 16

predict_config:
  filepaths: data/processed/small_set_filepaths.csv
  checkpoint: experiments/td_small_set_full_size_mdlite/results/version_1/time_distributed.ckpt
  skip_load_validation: True
  batch_size: 1
  num_workers: 5
  gpus: 1
